[project]
name = "FastAPI-app"
version = "0.1.0"
description = "SafeDriver Monitoring System"

readme = "README.md"
requires-python = ">=3.11"

[project.dependencies]
dependencies = "requirements.txt"

[project.optional-dependencies]
dev-requirements = {file = "dev-requirements.txt"}
